language: node_js
node_js: '7.8.0'

cache:
  - bundler: true
  - directories:
    - $HOME/.rvm
    - $HOME/.nvm
    - node_modules

before_install:
  - rvm install 2.1
  - rvm use 2.1
  - gem install bundler
  - bundle check || bundle install

install:
  - npm install -g firebase-tools

before_script:
  - export TZ=Asia/Jayapura
  - date
  - npm install gulp gulp-shell gulp-minify-html gulp-clean-css gulp-autoprefixer gulp-uncss gulp-download
  - npm install gulp-imagemin imagemin-pngquant imagemin-jpegtran imagemin-gifsicle gulp-minify
  - npm install gulp-replace fs gulp-concat gulp-uglify run-sequence gulp-rename gulp-minify-inline
  - npm install gulp-pixrem

script: 
  - gulp deploy
  - ls ./_site/assets/themes/twitter/js/

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  email:
    on_success: never
    on_failure: always

sudo: false
