language: node_js
node_js: '7.8.0'

cache:
  - bundler: true
  - directories:
    - _site
    - $HOME/.rvm
    - $HOME/.nvm

before_install:
  - rvm install 2.1
  - rvm use 2.1
  - gem install bundler
  - bundle check || bundle install

install:
  - npm install -g firebase-tools

before_script:
  - export TZ=Asia/Jayapura
  - date
  - npm install gulp

script: gulp deploy

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

branches:
  only:
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

notifications:
  email:
    on_success: never
    on_failure: always

sudo: false
